config/routes.rb
Csvtest::Application.routes.draw do
  get "csv/import"
  post "csv/import" => 'csv#upload'

  resources :scheduled_posts

  resources :reenactments

  resources :characters

  resources :users

end

app/models/scheduled_post.rb
class ScheduledPost < ActiveRecord::Base
  belongs_to :character
  belongs_to :reenactment
end

app/controllers/scheduled_posts_controller.rb
class ScheduledPostsController < ApplicationController
  # GET /scheduled_posts
  # GET /scheduled_posts.xml
  def index
    @scheduled_posts = ScheduledPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scheduled_posts }
    end
  end

  # GET /scheduled_posts/1
  # GET /scheduled_posts/1.xml
  def show
    @scheduled_post = ScheduledPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scheduled_post }
    end
  end

  # GET /scheduled_posts/new
  # GET /scheduled_posts/new.xml
  def new
    @scheduled_post = ScheduledPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scheduled_post }
    end
  end

  # GET /scheduled_posts/1/edit
  def edit
    @scheduled_post = ScheduledPost.find(params[:id])
  end

  # POST /scheduled_posts
  # POST /scheduled_posts.xml
  def create
    @scheduled_post = ScheduledPost.new(params[:scheduled_post])

    respond_to do |format|
      if @scheduled_post.save
        format.html { redirect_to(@scheduled_post, :notice => 'Scheduled post was successfully created.') }
        format.xml  { render :xml => @scheduled_post, :status => :created, :location => @scheduled_post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scheduled_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scheduled_posts/1
  # PUT /scheduled_posts/1.xml
  def update
    @scheduled_post = ScheduledPost.find(params[:id])

    respond_to do |format|
      if @scheduled_post.update_attributes(params[:scheduled_post])
        format.html { redirect_to(@scheduled_post, :notice => 'Scheduled post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scheduled_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_posts/1
  # DELETE /scheduled_posts/1.xml
  def destroy
    @scheduled_post = ScheduledPost.find(params[:id])
    @scheduled_post.destroy

    respond_to do |format|
      format.html { redirect_to(scheduled_posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/scheduled_posts_helper.rb
module ScheduledPostsHelper
end

app/views/scheduled_posts/_form.html.erb
<%= form_for(@scheduled_post) do |f| %>
  <% if @scheduled_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scheduled_post.errors.count, "error") %> prohibited this scheduled_post from being saved:</h2>

      <ul>
      <% @scheduled_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :reenactment_id %><br />
    <%= f.text_field :reenactment_id %>
  </div>
  <div class="field">
    <%= f.label :character_id %><br />
    <%= f.text_field :character_id %>
  </div>
  <div class="field">
    <%= f.label :postdate %><br />
    <%= f.text_field :postdate %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scheduled_posts/edit.html.erb
<h1>Editing scheduled_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @scheduled_post %> |
<%= link_to 'Back', scheduled_posts_path %>

app/views/scheduled_posts/index.html.erb
<h1>Listing scheduled_posts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Reenactment</th>
    <th>character</th>
    <th>Post Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scheduled_posts.each do |scheduled_post| %>
  <tr>
    <td><%= scheduled_post.content %></td>
    <td><%= scheduled_post.reenactment_id %></td>
    <td><%= scheduled_post.character_id %></td>
    <td><%= scheduled_post.postdate %></td>
    <td><%= link_to 'Show', scheduled_post %></td>
    <td><%= link_to 'Edit', edit_scheduled_post_path(scheduled_post) %></td>
    <td><%= link_to 'Destroy', scheduled_post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scheduled post', new_scheduled_post_path %>

app/views/scheduled_posts/new.html.erb
<h1>New scheduled_post</h1>

<%= render 'form' %>

<%= link_to 'Back', scheduled_posts_path %>

app/views/scheduled_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @scheduled_post.content %>
</p>

<p>
  <b>Reenactment:</b>
  <%= @scheduled_post.reenactment_id %>
</p>

<p>
  <b>character:</b>
  <%= @scheduled_post.character_id %>
</p>

<p>
  <b>postdate:</b>
  <%= @scheduled_post.postdate %>
</p>

<%= link_to 'Edit', edit_scheduled_post_path(@scheduled_post) %> |
<%= link_to 'Back', scheduled_posts_path %>