config/routes.rb
Csvtest::Application.routes.draw do
  get "csv/import"
  post "csv/import" => 'csv#upload'

  resources :scheduled_posts

  resources :reenactments

  resources :characters

  resources :users

end

app/models/reenactment.rb
class Reenactment < ActiveRecord::Base
  has_many :scheduled_post
end

app/controllers/reenactments_controller.rb
class ReenactmentsController < ApplicationController
  # GET /reenactments
  # GET /reenactments.xml
  def index
    @reenactments = Reenactment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reenactments }
    end
  end

  # GET /reenactments/1
  # GET /reenactments/1.xml
  def show
    @reenactment = Reenactment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reenactment }
    end
  end

  # GET /reenactments/new
  # GET /reenactments/new.xml
  def new
    @reenactment = Reenactment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reenactment }
    end
  end

  # GET /reenactments/1/edit
  def edit
    @reenactment = Reenactment.find(params[:id])
  end

  # POST /reenactments
  # POST /reenactments.xml
  def create
    @reenactment = Reenactment.new(params[:reenactment])

    respond_to do |format|
      if @reenactment.save
        format.html { redirect_to(@reenactment, :notice => 'Reenactment was successfully created.') }
        format.xml  { render :xml => @reenactment, :status => :created, :location => @reenactment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reenactment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reenactments/1
  # PUT /reenactments/1.xml
  def update
    @reenactment = Reenactment.find(params[:id])

    respond_to do |format|
      if @reenactment.update_attributes(params[:reenactment])
        format.html { redirect_to(@reenactment, :notice => 'Reenactment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reenactment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reenactments/1
  # DELETE /reenactments/1.xml
  def destroy
    @reenactment = Reenactment.find(params[:id])
    @reenactment.destroy

    respond_to do |format|
      format.html { redirect_to(reenactments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/reenactments_helper.rb
module ReenactmentsHelper
end

app/views/reenactments/_form.html.erb
<%= form_for(@reenactment) do |f| %>
  <% if @reenactment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reenactment.errors.count, "error") %> prohibited this reenactment from being saved:</h2>

      <ul>
      <% @reenactment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desciprtion %><br />
    <%= f.text_field :desciprtion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reenactments/edit.html.erb
<h1>Editing reenactment</h1>

<%= render 'form' %>

<%= link_to 'Show', @reenactment %> |
<%= link_to 'Back', reenactments_path %>

app/views/reenactments/index.html.erb
<h1>Listing reenactments</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Desciprtion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reenactments.each do |reenactment| %>
  <tr>
    <td><%= reenactment.title %></td>
    <td><%= reenactment.desciprtion %></td>
    <td><%= link_to 'Show', reenactment %></td>
    <td><%= link_to 'Edit', edit_reenactment_path(reenactment) %></td>
    <td><%= link_to 'Destroy', reenactment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reenactment', new_reenactment_path %>

app/views/reenactments/new.html.erb
<h1>New reenactment</h1>

<%= render 'form' %>

<%= link_to 'Back', reenactments_path %>

app/views/reenactments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @reenactment.title %>
</p>

<p>
  <b>Desciprtion:</b>
  <%= @reenactment.desciprtion %>
</p>


<%= link_to 'Edit', edit_reenactment_path(@reenactment) %> |
<%= link_to 'Back', reenactments_path %>